### ISSUE TITLE
find issues

### ISSUE THREAD

**Issue by renjiezhang** [renjiezhang/CAS-741#7]
@smiths 
Hello Prof,

I am not clear with the colleague issues. Base on the repos.xlsx, my job is to find issues from Smith,Geneva Marie's SRS and I need to add Zhao,Yuzhi as my colleague and let him find issues from mine.
Is that correct?

Thanks,
Renjie

**Comment by smiths** [comment]
Your interpretation is correct.  You need to review Geneva's work and provide her with comments (issues) and your work will be reviewed by Yuzhi.  That is, she will add issues to your repo.

I do not believe that you need to add Yuzhi as a member of your project.  Since the project is public, I believe she can post issues without you having to do anything.
