### ISSUE TITLE
6 Unit Testing Plan

### ISSUE THREAD

**Issue by renjiezhang** [renjiezhang/CAS-741#9]
@smiths 
Hello Prof,
For the V&V 6 Unit Testing Plan, is there any detailed template just as the #5??

Thanks

Renjie

**Comment by smiths** [comment]
The unit test plan does not have a detailed template for the V&V plan because it isn't possible to write detailed unit tests at this stage.  At this point you can only write about what you plan to do to determine your unit tests.  Since the design has not yet been documented (module guide), you do not yet know what modules will be unit tested.  You should focus on the criteria that you will use to determine the unit tests when the time comes.
